x-environment: &shared-env
  DB_USERNAME: depute
  DB_PASSWORD: ${DB_PASSWORD:-DeputeDB}
  DB_HOST: postgres
  DB_DATABASE: data

  REDIS_HOST: redis

  JWT_SECRET_KEY: ${JWT_SECRET:?}

  S3_ENDPOINT: ${S3_ENDPOINT:?}
  S3_REGION: ${S3_REGION:?}
  S3_ACCESS_KEY: ${S3_ACCESS_KEY:?}
  S3_SECRET_KEY: ${S3_SECRET_KEY:?}
  S3_BUCKET: ${S3_BUCKET:?}

  NATS_URL: nats://fake:user@nats:4222
  GOOGLE_DATA: ${GOOGLE_DATA:?}

services:
  web:
    image: depute-backend:latest
    restart: unless-stopped

    build:
      context: .
      dockerfile: Dockerfile

    command: python -m uvicorn --factory --host 0.0.0.0 --port 8080 --workers ${WEB_WORKERS:-4} --proxy-headers --forwarded-allow-ips="*" backend.presentation.web:create_app

    expose:
      - 8080

    environment: *shared-env

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  queues:
    image: depute-backend:latest
    restart: unless-stopped

    command: python -m taskiq workers --workers 1 backend.presentation.queues:broker backend.presentation.queues.task

    environment: *shared-env

    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started

  scheduler:
    image: depute-backend:latest
    restart: unless-stopped

    command: python -m taskiq scheduler backend.presentation.queues:scheduler backend.presentation.queues.task

    environment: *shared-env

    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started

  migrations:
    image: depute-backend:latest
    restart: no

    command: python -m alembic upgrade head

    environment: *shared-env

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17.1-alpine
    hostname: postgres
    restart: unless-stopped

    volumes:
      - pg-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: depute
      POSTGRES_PASSWORD: ${DB_PASSWORD:-DeputeDB}
      POSTGRES_DB: data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U depute -d data"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.1-alpine
    hostname: shared-redis
    restart: unless-stopped

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    restart: unless-stopped

    volumes:
      - nats:/data

    command: ["-js", "-sd=/data", "--user=fake", "--pass=user"]

volumes:
  pg-data:
  redis-data:
  nats:
