"""add visibility field to document

Revision ID: 14775805209b
Revises: 8a94a44b375e
Create Date: 2025-10-06 21:06:40.397881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14775805209b'
down_revision: Union[str, Sequence[str], None] = '8a94a44b375e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum = postgresql.ENUM('PUBLIC', 'PRIVATE', name='document_visibility')

def upgrade() -> None:
    """Upgrade schema."""
    enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('visibility', enum, server_default='PUBLIC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'visibility')
    enum.drop(op.get_bind())
    # ### end Alembic commands ###
