"""add visibility field to catalog

Revision ID: 189624e41093
Revises: a935d41a8e46
Create Date: 2025-10-07 12:34:02.865775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '189624e41093'
down_revision: Union[str, Sequence[str], None] = 'a935d41a8e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum = postgresql.ENUM('PUBLIC', 'PRIVATE', name='catalog_visibility')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    enum.create(op.get_bind())
    op.add_column('catalogs', sa.Column('visibility', enum, server_default='PUBLIC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogs', 'visibility')
    enum.drop(op.get_bind())
    # ### end Alembic commands ###
