"""add helping_to field & update enum for user

Revision ID: 64efc223d67a
Revises: 3c38c71da5b4
Create Date: 2025-10-07 18:12:19.883506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64efc223d67a'
down_revision: Union[str, Sequence[str], None] = '3c38c71da5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE user_roles ADD VALUE 'DEPUTE_HELPER';")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('helping_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_helping_to_id_users'), 'users', 'users', ['helping_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_helping_to_id_users'), 'users', type_='foreignkey')
    op.drop_column('users', 'helping_to_id')
    # ### end Alembic commands ###
