"""add reason_document_id field

Revision ID: 8a94a44b375e
Revises: 17430686cf9c
Create Date: 2025-10-06 20:39:31.276479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a94a44b375e'
down_revision: Union[str, Sequence[str], None] = '17430686cf9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_rsvp', sa.Column('reason_document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_events_rsvp_reason_document_id_documents'), 'events_rsvp', 'documents', ['reason_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_events_rsvp_reason_document_id_documents'), 'events_rsvp', type_='foreignkey')
    op.drop_column('events_rsvp', 'reason_document_id')
    # ### end Alembic commands ###
