"""add enum value

Revision ID: a10acce97f3b
Revises: 64efc223d67a
Create Date: 2025-10-08 15:29:39.268567

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a10acce97f3b"
down_revision: Union[str, Sequence[str], None] = "64efc223d67a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE event_statutes ADD VALUE 'STARTING_SOON';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
