"""create m2m relationship event_document

Revision ID: a935d41a8e46
Revises: 14775805209b
Create Date: 2025-10-07 09:09:52.739549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a935d41a8e46'
down_revision: Union[str, Sequence[str], None] = '14775805209b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_document',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_event_document_document_id_documents')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_document_event_id_events')),
    sa.PrimaryKeyConstraint('event_id', 'document_id', name=op.f('pk_event_document'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_document')
    # ### end Alembic commands ###
