"""create catalog model

Revision ID: b6d8d8bcf662
Revises: 196933c1112e
Create Date: 2025-10-06 20:10:47.489970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d8d8bcf662'
down_revision: Union[str, Sequence[str], None] = '196933c1112e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['catalogs.id'], name=op.f('fk_catalogs_parent_id_catalogs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalogs')),
    sa.UniqueConstraint('parent_id', 'name', name='uq_catalog_parent_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalogs')
    # ### end Alembic commands ###
