"""add created_by field to catalog

Revision ID: d801b98bfba3
Revises: 189624e41093
Create Date: 2025-10-07 12:40:23.280585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd801b98bfba3'
down_revision: Union[str, Sequence[str], None] = '189624e41093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogs', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_catalogs_created_by_id_users'), 'catalogs', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_catalogs_created_by_id_users'), 'catalogs', type_='foreignkey')
    op.drop_column('catalogs', 'created_by_id')
    # ### end Alembic commands ###
