"""add ends_at field

Revision ID: d9c3fd9e5bc6
Revises: e6ea51fe37bf
Create Date: 2025-10-06 16:30:46.463651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c3fd9e5bc6'
down_revision: Union[str, Sequence[str], None] = 'e6ea51fe37bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'ends_at')
    # ### end Alembic commands ###
